- package.json
- src/app.module.ts
- src/main.ts
- src/mongodb/dto/AssessmentInput.dto.ts
- src/mongodb/dto/CreateLearnerProfile.dto.ts
- src/mongodb/mongodb.module.ts
- src/mongodb/schemas/assessmentInput.schema.ts
- src/mongodb/schemas/scores.schema.ts
- src/mongodb/scores.controller.ts
- src/mongodb/scores.service.ts
New updates from this branch - 
1. Missing Tokens and Anomaly Tokens buckets creation and storing tokens with score in it
2. Create Separate Routes for Tamil, Kannada and Hindi for create learner vector
3. Mean & Median Calculation logic added. Used mean logic for calculate gettarget score
4. Swagger File integration done in project
5. Content API integrated. Create APIs for fetch content by userid and sessionid based on token, user milestone level
6. Python Text Eval API integarted in learner AI code and storing text eval matrices 
7. GetSetResult API created for calculating milestones and checking pass fail in set
8. Schema changes for Sub Session id , contentType, milestone_progress and contentId
> TASK #212370 All Learner AI 0.2 with new updates - Missing Tokens Bucket, Routes changes, Swagger file, Content & Text Eval API integration 

- src/mongodb/scores.controller.ts
- test/app.e2e-spec.ts
All 1.0 get assessment progress for the life and loss feature.
> All 1.0 get assessment progress

- src/mongodb/scores.controller.ts
Added life feature for the english language.
> Added life feature for the english language.

- src/mongodb/scores.controller.ts
- src/mongodb/scores.service.ts
- Add the changes in the update learner Profile api
- added the new service for the getTargetByContentId.
> calculate the target count by content_id added the new service for that.

- src/mongodb/scores.controller.ts
pass the totalSyllables from the client side.
> pass the totalSyllables from the client side.

- src/mongodb/scores.controller.ts
syllable criteria added for passing getSetResult.
> syllable criteria added for passing getSetResult.

- src/mongodb/scores.controller.ts
Threshold % change for the getSetResult.
> Threshold % change for the getSetResult.

- src/mongodb/scores.controller.ts
- src/mongodb/scores.service.ts
> All learner ai 0.3 telgu

- src/mongodb/scores.controller.ts
- src/mongodb/scores.service.ts
Get target api by multiple users api added
> Get target api by multiple users api added

- src/mongodb/scores.controller.ts
New api added for the famalarity and the milestone progress.
> New api added for the famalarity and the milestone progress.

- src/mongodb/schemas/scores.schema.ts
- src/mongodb/scores.controller.ts
- src/mongodb/scores.service.ts
Retry attribute feature added.
> Retry attribute feature added.

- src/mongodb/scores.service.ts
- Done for Famalarity & Targets.
> decimal point added in the getTarget for multiple users

- src/mongodb/scores.controller.ts
perf: update the syllable formula when syllabule_count us not provided.
> perf: update the syllable formula when syllabule_count us not provided

- src/app.controller.ts
- src/app.module.ts
- src/config/mongodb.config.ts
- src/config/mysql.config.ts
- src/main.ts
- src/mongodb/dto/AssessmentInput.dto.ts
- src/mongodb/dto/CreateLearnerProfile.dto.ts
- src/mongodb/mongodb.module.ts
- src/mongodb/schemas/assessmentInput.schema.ts
- src/mongodb/schemas/hexcodeMapping.schema.ts
- src/mongodb/schemas/scores.schema.ts
- src/mongodb/scores.controller.ts
- src/mongodb/scores.service.ts
- src/mysql/dto/create-score.dto.ts
- src/mysql/entities/score.entity.ts
- src/mysql/mysql.module.ts
- src/mysql/scores.controller.ts
- src/mysql/scores.service.ts
- test/app.e2e-spec.ts
Retry feature added and lint fix
> Retry feature added and lint fix

- src/mongodb/scores.controller.ts
- src/mongodb/scores.service.ts
All 1.0 test rig : Update learner Profile added.
> All 1.0 test rig : Update learner Profile added.

- src/mongodb/scores.controller.ts
- src/mongodb/scores.service.ts
perf: Created_At filed added in the get_user_profile Api
> perf: Created_At filed added in the get_user_profile Api

- src/mongodb/scores.controller.ts
- src/mongodb/scores.service.ts
Merge ALL 1.0 test rig to All 1.1 dev
> Merge ALL 1.0 test rig to All 1.1 dev

- src/mongodb/scores.controller.ts
- src/mongodb/scores.service.ts
fix: get_familirity service updated
> fix: get_familirity service updated

- src/mongodb/scores.controller.ts
- src/mongodb/scores.service.ts
Query changes for familiarity and the Target.
> Query changes for familiarity and the Target.

- package-lock.json
- package.json
- src/main.ts
Added the response compression
> feat: Added the response compression

- src/mongodb/scores.controller.ts
- src/mongodb/scores.service.ts
Added contentType as parameter to audio processing api
> Added contentType as parameter to audio processing api

- src/mongodb/mongodb.module.ts
- Connection pool for the Database added.
> perf: Connection pool added

- src/mongodb/scores.controller.ts
fix: removed the unwanted fields from the response data
> fix: removed the unwanted fields from the response data

- src/mongodb/scores.service.ts
> fix: session target issue fix

- src/mongodb/scores.controller.ts
- src/mongodb/scores.service.ts
Fix: swagger update for rest of apis
> Fix: swagger update for rest of apis

- src/mongodb/config/language/gu.ts
- src/mongodb/dto/CreateLearnerProfile.dto.ts
- src/mongodb/scores.controller.ts
- src/mongodb/scores.service.ts
Feat: New language Gujarati enable.
> Feat: New language Gujarati enable.

- src/mongodb/config/language/hi.ts
- src/mongodb/schemas/hexcodeMapping.schema.ts
- src/mongodb/scores.controller.ts
- src/mongodb/scores.service.ts
> All 2.0 dev hindi update

- src/mongodb/scores.controller.ts
Feat: Add the swagger for the updated apis
> Feat: Add the swagger for the updated apis

- src/mongodb/scores.controller.ts
- src/mongodb/scores.service.ts
Fix:Add the token changes in the gujarati api
> Fix:Add the token changes in the gujarati api

- src/mongodb/scores.controller.ts
- src/mongodb/scores.service.ts
> All learner gu update

- src/mongodb/dto/CreateLearnerProfile.dto.ts
- src/mongodb/schemas/scores.schema.ts
- src/mongodb/scores.controller.ts
- src/mongodb/scores.service.ts
Feat: Update the get_set_result and ULP_api for new mechanics
> Feat: Update the get_set_result and ULP_api for new mechanics

- src/mongodb/scores.controller.ts
Feat: add the createScoreData in the response data
> Feat: add the createScoreData in the response data

- src/mongodb/scores.controller.ts
Fix:Add the score for the correct choice
> Fix:Add the score for the correct choice

- .github/workflows/dev.yml
> Merge story mode feature 

- src/app.controller.ts
- src/main.ts
> Feat: Add the health api

- src/mongodb/config/language/en.ts
- src/mongodb/config/language/ta.ts
- src/mongodb/scores.controller.ts
Tamil and English max level set from config
> Tamil and English max level set from config

- src/app.controller.ts
> Feat:Added the health api

- src/mongodb/dto/CreateLearnerProfile.dto.ts
- src/mongodb/schemas/scores.schema.ts
- src/mongodb/scores.controller.ts
mechanics_id added in learner data schema and api
> mechanics_id added in learner data schema and api

- src/mongodb/scores.controller.ts
Feat: update the get_set_result api for the odiya language
> Feat: update the get_set_result api for the odiya language

- src/auth/auth.guard.ts
- src/mongodb/scores.controller.ts
- 1. Added the check for the content limit
- 2. Removed the user_id from the query param and take it from the token.
- 3. Console removed.
> Release 2.0 dev vapt auth 4.1

- src/mongodb/scores.controller.ts
Fix : Current Leve; & previous_level not chnage issue fixed;
> Fix : Current Leve; & previous_level not chnage issue fixed;

- src/auth/auth.guard.ts
- src/auth/auth.module.ts
- src/mongodb/mongodb.module.ts
- src/mongodb/scores.controller.ts
> Vapt release 1.3 test rig

- package-lock.json
- package.json
- src/auth/auth.guard.ts
- src/mongodb/scores.controller.ts
- src/mongodb/scores.service.ts
- Changes
1. Convert the token from jwt to JOSE
2. Add the content limit for the getContent char/word/sentence/para apis
3. Removed the unwanted console log
> Feat: Convert the token from JWT to JOSE

- src/mongodb/dto/CreateLearnerProfile.dto.ts
- src/mongodb/scores.controller.ts
Feat: get user_id from the token for the required apis
> Feat: get user_id from the token for the required apis

- src/mongodb/schemas/scores.schema.ts
- src/mongodb/scores.controller.ts
- src/mongodb/scores.service.ts
> Prosody and Fluency Changes

- .github/workflows/prod-test-rig.yml
- src/app.controller.ts
- Merge The branch relsease-1.3 to release-1.3-test rig
> Release 1.3 test rig

- src/mongodb/dto/CreateLearnerProfile.dto.ts
- src/mongodb/schemas/scores.schema.ts
- src/mongodb/scores.controller.ts
Reverts Sunbird-ALL/all-learner-ai-services#160
> Revert "TaskId #238424 task : Integrate LLM in ULP API and handle getsetResult"
